name: Deploy GAS (Matching)

on:
  push:
    paths:
      - 'gas_matching/**'
      - '.github/workflows/deploy-gas-matching.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASP_CLIENT_ID: ${{ secrets.CLASP_CLIENT_ID }}
          CLASP_CLIENT_SECRET: ${{ secrets.CLASP_CLIENT_SECRET }}
          CLASP_REFRESH_TOKEN: ${{ secrets.CLASP_REFRESH_TOKEN }}
        run: |
          printf '%s\n' \
            "{\"token\":{\"refresh_token\":\"$CLASP_REFRESH_TOKEN\"},\"oauth2ClientSettings\":{\"clientId\":\"$CLASP_CLIENT_ID\",\"clientSecret\":\"$CLASP_CLIENT_SECRET\"}}" \
            > ~/.clasprc.json

      - name: Push to GAS
        run: |
          cd gas_matching
          clasp push --force
