name: Reusable GAS Deploy

on:
  workflow_call:
    inputs:
      dir:               # 例: gas/uploader
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASP_CLIENT_ID:     ${{ secrets.CLASP_CLIENT_ID }}
          CLASP_CLIENT_SECRET: ${{ secrets.CLASP_CLIENT_SECRET }}
          CLASP_REFRESH_TOKEN: ${{ secrets.CLASP_REFRESH_TOKEN }}
        run: |
          cat > ~/.clasprc.json <<EOF
          {
            "token": {
              "refresh_token": "${CLASP_REFRESH_TOKEN}"
            },
            "oauth2ClientSettings": {
              "clientId":     "${CLASP_CLIENT_ID}",
              "clientSecret": "${CLASP_CLIENT_SECRET}",
              "redirectUri":  "http://localhost"
            },
            "isLocalCreds": false
          }
          EOF

      - name: Push to GAS
        run: |
          cd "${{ inputs.dir }}"
          clasp push --force
