name: Reusable GAS Deploy

on:
  workflow_call:
    inputs:
      dir:
        required: true     # 例: 'gas/uploader' など
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASP_CLIENT_ID: ${{ secrets.CLASP_CLIENT_ID }}
          CLASP_CLIENT_SECRET: ${{ secrets.CLASP_CLIENT_SECRET }}
          CLASP_REFRESH_TOKEN: ${{ secrets.CLASP_REFRESH_TOKEN }}
        run: |
          printf '{"token":{"refresh_token":"%s"},"oauth2ClientSettings":{"clientId":"%s","clientSecret":"%s"}}' \
            "$CLASP_REFRESH_TOKEN" "$CLASP_CLIENT_ID" "$CLASP_CLIENT_SECRET" > ~/.clasprc.json

      - name: Push to GAS
        run: |
          cd "${{ inputs.dir }}"
          clasp push --force
