name: GAS Deploy (Matching)

on:
  push:
    paths:
      - 'gas/matching/**'
      - '.github/workflows/gas-matching.yml'

jobs:
  call-deploy:
    uses: ./.github/workflows/gas-deploy.yml
    secrets: inherit              # ★ 追加
    with:
      dir: gas/matching
