name: GAS Deploy (Uploader)

on:
  push:
    paths:
      - 'gas/uploader/**'
      - '.github/workflows/gas-uploader.yml'

jobs:
  call-deploy:
    uses: ./.github/workflows/gas-deploy.yml
    secrets: inherit              # ★ 追加
    with:
      dir: gas/uploader
